apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: mahmoudamr/jenkins_image02:latest
        ports:
        - containerPort: 5000
        env:
        - name: ENV_VAR
          value: "value"
